version: "3.4"

services:
  api:
    build: .
    container_name: api
    hostname: api
    ports:
      - "8080:8001"
    restart: unless-stopped
  db:
    image:
    container_name: db
    hostname: db